export {
  DATASET_FILE_NAME,
  MANIFEST_FILE_NAME,
  buildAtlasDataset,
  createDatasetManifest,
  mergePublishedProposals,
  prepareAtlasDataset,
  selectPreviousDataset,
  serializeDataset,
  writeAtlasDataset,
} from './dataset.js';
export {
  DATASET_SCHEMA_VERSION,
  atlasDatasetSchema,
  atlasProposalSchema,
  datasetManifestSchema,
  parseAtlasDataset,
  parseDatasetManifest,
  proposalChangeKindSchema,
  proposalChangeKinds,
  proposalChangeSchema,
  overviewSchema,
  translationCacheEntrySchema,
  proposalSnapshotSchema,
  proposalStageSchema,
  proposalStages,
  proposalStatusSchema,
  proposalStatuses,
  proposalSummarySchema,
  translationMetadataSchema,
  type AtlasDataset,
  type AtlasProposal,
  type DatasetManifest,
  type KeywordMode,
  type ProposalChange,
  type ProposalChangeKind,
  type ProposalDetail,
  type ProposalFilter,
  type ProposalOverview,
  type ProposalSnapshot,
  type ProposalStage,
  type ProposalStatus,
  type ProposalSummary,
  type SyncedProposal,
  type TranslationMetadata,
  type TranslationCacheEntry,
} from './model.js';
export {
  getProposalChanges,
  getProposals,
  searchProposals,
} from './queries.js';
export { fetchTc39Proposals } from './source.js';
export { detectProposalChanges, mergeProposalChanges } from './sync.js';
export {
  AGENT_TRANSLATIONS_FILE,
  TRANSLATION_PLAN_FILE,
  TRANSLATION_SNAPSHOT_FILE,
  agentTranslationsSchema,
  createTranslationPlan,
  executeTranslationWork,
  scanTranslationWork,
  translationPlanSchema,
  type AgentTranslations,
  type ExecuteTranslationResult,
  type ScanTranslationResult,
  type TranslationPlan,
  type TranslationReason,
  type TranslationWorkflowOptions,
} from './translation-workflow.js';
export {
  TRANSLATION_CONTRACT_VERSION,
  TRANSLATION_TARGET_LANGUAGE,
  applyProposalTranslation,
  proposalNeedsTranslation,
  translatePendingProposals,
  translatePendingProposalsFromEnv,
  translationCacheKey,
  translationContentHash,
  translationFingerprint,
  type ProposalTranslator,
  type TranslationOutput,
  type TranslationCacheKeyOptions,
  type TranslationContent,
  type TranslationRun,
  type TranslationRunResult,
} from './translation.js';
